var TEXT_HELP_TITLE         = "HOW TO PLAY";

var TEXT_HELP1              = "PLACE ALL YOUR PIECES (MEN) ON BOARD AND MOVE THEM TO FORM A LINE OF 3 PIECES (A MILL).";
var TEXT_HELP2              = "ONCE YOU FORM A MILL, YOU CAN REMOVE ONE OF YOUR OPPONENT'S MEN. BREAK A MILL TO UNLOCK THE MILLS AGAIN.";
var TEXT_HELP3              = "PIECES FROM A FORMED MILL CAN'T BE REMOVED UNLESS NO OTHER MEN ARE AVAILABLE.";
var TEXT_HELP4              = "YOUR AIM IS TO LEAVE YOUR OPPONENT WITH EITHER 2 PIECES OR 0 MOVES!";
        
var TEXT_MODE               = "CHOOSE GAME MODE";

var TEXT_STATE0             = "SET YOUR MEN ON THE BOARD";
var TEXT_STATE1             = "REMOVE A MAN FROM THE OPPONENT'S";
var TEXT_STATE2             = "MOVE YOUR MEN TO CREATE A MILL";

var TEXT_TURN               = "PLAYER TURN";
var TEXT_SCORE              = "SCORE";

var TEXT_PLAYERBLACKWINS    = "BLACK PLAYER WINS!";
var TEXT_PLAYERWHITEWINS    = "WHITE PLAYER WINS!";
var TEXT_YOUWIN             = "YOU WIN!";
var TEXT_YOULOSE            = "YOU LOSE!";

var TEXT_NOMOVEMENT         = "NO MORE MOVEMENTS!";
var TEXT_NOPIECE            = "NOT ENOUGH MEN LEFT!";
var TEXT_PIECEINMILL        = "YOU CAN'T REMOVE A MAN IN A MILL, IF THERE ARE FREE MEN";
var TEXT_ARE_SURE           = "ARE YOU SURE YOU WANT TO EXIT? ALL UNSAVED PROGRESS WILL BE LOST";

var TEXT_CREDITS_DEVELOPED  = "DEVELOPED BY";
var TEXT_ERR_LS             = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";