var CANVAS_WIDTH = 768;
var CANVAS_HEIGHT = 1400;
var CANVAS_WIDTH_HALF = CANVAS_WIDTH / 2;
var CANVAS_HEIGHT_HALF = CANVAS_HEIGHT / 2;

var EDGEBOARD_X = 10;
var EDGEBOARD_Y = 265;

var FPS = 30;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "arial-webfont";
var PRIMARY_FONT_COLOUR = "#ffffff";
var SECONDARY_FONT_COLOUR = "#000000";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;

var WIN_SCORE;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;

var MODE_HUMAN    = 0;
var MODE_COMPUTER = 1;

var WHITE_PLAYER = 0;
var BLACK_PLAYER = 1;

var START_PIECES = 9;

var GAME_STATE_DISPOSITION = 0;
var GAME_STATE_REMOVING = 1;
var GAME_STATE_MOVEMENT = 2;

var PIECES_POINTS;

var TIMER_AI = 1000;               // A.I. TIMER (IN MS)
var PIECE_MOVEMENT_SPEED = 500;